project:
  type: website
  output-dir: docs

website:
  title: "NerusSkyhigh's Personal Blog"
  navbar:
    right:
      - about.qmd
      - posts/00_Projects/index.qmd
      - text: "Resumé"
        href: https://nerusskyhigh.github.io/online-cv/
      - icon: github
        href: https://github.com/nerusskyhigh
format:
  html:
    theme: superhero
    css: styles.css



