project:
  type: website
  output-dir: _site

website:
  title: "NerusSkyhigh's Personal Blog"
  navbar:
    right:
      - index.qmd
      - Projects/index.qmd
      - text: "CV"
        href: index.qmd
      - text: " "
      - icon: github
        href: https://github.com/nerusskyhigh
      - icon: linkedin
        href: https://www.linkedin.com/in/guglielmo-grillo/
      - icon: envelope
        href: mailto:cv@guglielmogrillo.com
format:
  html:
    theme: superhero
    css: styles.css



